### ISSUE TITLE
How to build SE 300d - BM25 embedding?

### ISSUE THREAD

**Issue by leeivan** [neuml/codequestion#16]
Currently, the model is using BM25 + fastText for indexing, but how to use SE 300d - BM25 and ParaNMT - BM25, I want to evaluate them.

**Comment by davidmezzetti** [comment]
Thank you for checking codequestion out. My understanding is you're looking to reproduce the results below:

**StackExchange Query**

Models scored using Mean Reciprocal Rank (MRR)

| Model           | MRR   | 
| --------------- | :---: |
| SE 300d - BM25  | 76.3  |
| ParaNMT - BM25  | 67.4  |
| FastText - BM25 | 66.1  |
| BM25            | 49.5  |
| TF-IDF          | 45.9  |

**STS Benchmark**

Models scored using Pearson Correlation

| Model           | Supervision   | Dev   | Test  |
| --------------- | :-----------: | :---: | :---: |
| ParaNMT - BM25  | Train         | 82.6  | 78.1  |
| FastText - BM25 | Train         | 79.8  | 72.7  |
| SE 300d - BM25  | Train         | 77.0  | 69.1  |

- The default model is SE 300d
- fastText uses the pre-trained [Common Crawl 600B](http://magnitude.plasticity.ai/fasttext/light/crawl-300d-2M.magnitude)
- ParaNMT vectors were built using the txt file in [this archive file](https://github.com/kawine/usif/blob/master/paranmt.tar.gz) converted to pymagnitude vectors using the following command (installed as a dependency of codequestion via txtai). 
  ```
  python -m pymagnitude.converter -i paranmt.txt -o paranmt.magnitude
  ```

For each set of vectors, you need to build an index and run the STS tests. 

- Build a function similar to run in [index.py](https://github.com/neuml/codequestion/blob/master/src/python/codequestion/index.py#L81) using the new vector model
- Run [STS Tests](https://github.com/neuml/codequestion#testing)

**Comment by davidmezzetti** [comment]
Marking this issue as resolved, re-open if issues still persist
