### ISSUE TITLE
UserWarning: Trying to unpickle estimator TruncatedSVD from version 0.23.1 when using version 0.23.2

### ISSUE THREAD

**Issue by lazyoracle** [neuml/codequestion#17]
```bash
~/miniconda3/envs/deepl/lib/python3.8/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator TruncatedSVD from version 0.23.1 when using version 0.23.2. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(
codequestion query shell
```

Received the warning above when launching `codequestion` `shell` after a fresh install.

System details:
* Ubuntu 18.04
* Miniconda Python 3.8
* CPU-only `pytorch 1.6`

**Comment by davidmezzetti** [comment]
This is a benign warning, the process will run fine. But I am working to update the models and will ensure the pretrained model is built with the latest version of scikit-learn.

**Comment by davidmezzetti** [comment]
Thank you for checking codequestion out and taking the time to file an issue. 

This is a benign warning, the process will run fine. But I am working to update the models and will ensure the pretrained model is built with the latest version of scikit-learn.

**Comment by davidmezzetti** [comment]
Thank you for checking codequestion out and taking the time to file an issue.

This is a benign warning, the process will run fine. But I am working to update the models and will ensure the pretrained model is built with the latest version of scikit-learn.

In the meantime, you can run the following to get rid of the error.

```
python -m codequestion.index
```

**Comment by davidmezzetti** [comment]
Marking this issue as resolved
