### ISSUE TITLE
Vector model file not found

### ISSUE THREAD

**Issue by chicham** [neuml/codequestion#2]
Hello, 

Thank you very much for the project. But I have one small issue, right now it seems that when you run `python -m codequestion.download` it downloads a configuration file that will be used by codequestion to load the model.

The path to the model seems hardcoded to `/home/dmezzett/.codequestion/vectors/stackexchange-300d.magnitude`
How can we specify to codequestion to use our home or modify the config file?  

Best

**Comment by davidmezzetti** [comment]
Thank you for reporting this, I'm working on an updated version of codequestion backed by txtai. I will make sure to resolve this issue with that release.

In terms of a workaround, the config file is just a dict object that was pickled to a file. If you open a python shell in ~/.codequestion/models and edit/run the following code, if should workaround the issue:

```
import pickle

with open("config", "rb") as handle:
    config = pickle.load(handle)

config["path"] = "/<your home directory>/.codequestion/vectors/stackexchange-300d.magnitude"

with open("config", "wb") as handle:
    pickle.dump(config, handle, protocol=pickle.HIGHEST_PROTOCOL)
```

**Comment by chicham** [comment]
Thanks for your quick response !

**Comment by belvederef** [comment]
I just want to point out to newcomers that the script proposed by davidmezzetti should be run in the "stackexchange folder". Btw, thanks for this amazing package!
