### ISSUE TITLE
Vector model file not found (cord19-300d.magnitude)

### ISSUE THREAD

**Issue by fomar1994** [neuml/codequestion#20]
Hi,

I get the following error when running python -m paperai.index

	raise IOError(ENOENT, "Vector model file not found", path)
	FileNotFoundError: [Errno 2] Vector model file not found: 'C:\\Users\\x\\.cord19\\vectors\\cord19-300d.magnitude'

PS. I am quite new to all this; so, apologies if the mistake is on my end.

**Comment by davidmezzetti** [comment]
Thank you for reporting this issue. Can you create this in the [paperai project](https://github.com/neuml/paperai)? codequestion is a separate project. 

You need to download the pre-trained vectors: https://github.com/neuml/paperai#building-a-model
