### ISSUE TITLE
Feature Request: Run args and output without staying in the question shell

### ISSUE THREAD

**Issue by FruityWelsh** [neuml/codequestion#4]
It would be nice to be able to use more like a cl tool where you could just type: ```codequestion "how do I iterate a list in python"```.

**Comment by davidmezzetti** [comment]
Thank you for the idea.

One current way you can do this is by running:

python -m codequestion.query "how do I iterate a list in python"

**Comment by davidmezzetti** [comment]
Closing this issue given that there is a way to call via the command line. A simple command line alias i.e. alias cqq='python -m codequestion.query' can be created to make it easier to call.

Issue #12 will add functionality to call a service vs loading the model each invocation. Currently, the shell exists to keep a preloaded instance active within a single process.
