### ISSUE TITLE
Feature Request: Code language preference config

### ISSUE THREAD

**Issue by FruityWelsh** [neuml/codequestion#5]
It is would be nice to be able to list coding language preference so you are more likly to answers relevant to you when you fail to specify the lang

**Comment by davidmezzetti** [comment]
For another project backed by txtai, the query language had a hook to require a term. For example, you could do "+python find in list" and it would only return matches if Python was in the text or a tag.

Is this what you had in mind?

**Comment by FruityWelsh** [comment]
something like that, basically something to say "How do I do X?" and be able to avoid "in python/javascript/rust/etc" by default. Just an annoyance I've run into with these kind of language queries and seems possibly solvable in cl tool like this.

Maybe options maybe better suited to the task? So something like ```codequestion --py how do I itterate a list``` for python answers, and ```codequestion --rs how do I iterate a list``` for rust answers. 
What I was thinking of first though was something like an env var ```CODEQUESTION_DEFAULT_LANG``` which could be set to whatever language you primally code in.

Really like the tool so far by the way :)

Edit:
made the ```py```, ```rs``` options example double lined options from single lines to keep them inline with normal command line standards.

**Comment by davidmezzetti** [comment]
Added default language to query and shell
