### ISSUE TITLE
How to Speed Up Embeddings 10 Million Text

### ISSUE THREAD

**Issue by mustfkeskin** [neuml/codequestion#7]
I have 10 Million text documents

```
# Build embeddings index
embeddings.index(Index.stream(texts))
```

This part of code run too slowly 
How i can run faster this part

**Comment by davidmezzetti** [comment]
Thank you for using codequestion. Couple questions that will help determine what ideas are best to improve performance. 

- The indexing process is multi-threaded, it will use all available cores. How many CPU cores do you have?
- How are texts being generated in the call to Index.streams
- How slow is slow and what are your expectations for time to complete?

**Comment by mustfkeskin** [comment]
- I have 8 cpu core
- Texts generated in the call to Index.streams
- My expectation like 1 hour  but code still running more than 3 hours

**Comment by davidmezzetti** [comment]
It sounds like you have a local source version of codequestion running? If that is the case, I would see how long it takes to run through Index.stream without indexing to ensure the texts are being generated fast enough.

It is also possible that the call to pool.imap in blocking against itself. 

Embeddings.py line 139:

```python
for uid, embedding in pool.imap(transform, documents):
```

can add batching via a chunksize

```python
for uid, embedding in pool.imap(transform, documents, 500):
```

If you're running directly against the source, that is something you could try out to see if it improves the runtime. 

I am in the process of migrating all the embedding logic to depend on the txtai library (already happening in the master branch). As part of that, I can look into improving the streaming/batching of data in the call above.

**Comment by mustfkeskin** [comment]
Thanks for your answer, I will try without index.stream and batching than i will share the results

**Comment by davidmezzetti** [comment]
@mustfkeskin Any luck/progress on this?

**Comment by davidmezzetti** [comment]
Marking this issue as resolved. Re-open if there is further conversation/issues to research.
